name: Nightly build

on:
  schedule:
    - cron: '*/6 * * * *' # At 02:30 GMT+8
jobs:
  nightly-build:
    runs-on: ubuntu-latest
    steps:
      - uses: JohnNiang/actions/halo-next-docker-build@main
        with:
          image-name: halodev
          # ghcr-token: ${{ secrets.GHCR_TOKEN }}
          push: false
          checkout-from: next
